# Site settings
title: unfoldingWord
email: info@unfoldingWord.org
description: Unrestricted Biblical content in every language
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://unfoldingword.org" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

keep_files: [assets]

# Build settings
markdown: kramdown


