# Site settings
title: unfoldingWord
email: info@unfoldingWord.org
description: Unrestricted biblical content in every language
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://unfoldingword.org" # the base hostname & protocol for your site
twitter_username: unfoldingWord
github_username:  jekyll

keep_files: [assets, assets/docs]

gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown


